"""
C1 Signal Parity: GreenblattWeekly

Verifies that AlphaLive's signal engine produces IDENTICAL signals to
AlphaLab's GreenblattWeekly backtest engine on the same weekly bar data.

Fixture: AAPL weekly bars 2015-2024 (473 bars after SMA_50/RSI warmup).
Expected signals generated by AlphaLab on 2026-05-04.

Non-HOLD signals in fixture:
  bar   3  BUY - weekly RSI oversold (32.7 < 35)
  bar 153  SELL - trailing stop fired (20% below peak)
  bar 156  BUY - weekly RSI oversold (34.8 < 35)
  bar 222  SELL - trailing stop fired (20% below peak)
  bar 352  BUY - weekly 10w/50w golden cross

Run: pytest tests/test_greenblatt_parity.py -v
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

import pandas as pd
import pytest

PROJECT_ROOT = Path(__file__).parent.parent

from alphalive.strategy.signal_engine import SignalEngine
from alphalive.strategy_schema import StrategySchema

FIXTURE_PATH  = PROJECT_ROOT / "tests" / "fixtures" / "aapl_weekly_fixture.csv"
EXPECTED_PATH = PROJECT_ROOT / "tests" / "fixtures" / "expected_signals_greenblatt_weekly.csv"

STRATEGY_PARAMS = {
    "fast_sma": 10,
    "slow_sma": 50,
    "rsi_period": 14,
    "rsi_oversold": 35,
    "rsi_overbought": 65,
    "min_hold_bars": 52,
    "trailing_stop_fraction": 0.20,
    "exit_rsi_overbought": False,
    "exit_sma_cross": False,
}


def _make_config(ticker: str = "AAPL") -> StrategySchema:
    return StrategySchema(
        schema_version="1.0",
        strategy={"name": "greenblatt_weekly", "parameters": STRATEGY_PARAMS},
        ticker=ticker,
        timeframe="1Week",
        risk={
            "stop_loss_pct": 25.0,
            "take_profit_pct": 100.0,
            "max_position_size_pct": 33.0,
            "max_daily_loss_pct": 10.0,
            "max_open_positions": 1,
            "portfolio_max_positions": 10,
        },
        execution={"order_type": "market"},
        safety_limits={},
        metadata={
            "exported_from": "C1-ParityTest",
            "exported_at": datetime.now().isoformat(),
            "alphalab_version": "1.0.0",
            "backtest_id": "parity_greenblatt_weekly",
            "backtest_period": {"start": "2015-01-01", "end": "2024-12-31"},
            "performance": {
                "sharpe_ratio": 1.22,
                "sortino_ratio": 1.34,
                "total_return_pct": 44.88,
                "max_drawdown_pct": -11.32,
                "win_rate_pct": 100.0,
                "profit_factor": 999.0,
                "total_trades": 7,
                "calmar_ratio": 1.64,
            },
        },
    )


def _load_fixture() -> pd.DataFrame:
    df = pd.read_csv(FIXTURE_PATH)
    df["timestamp"] = pd.to_datetime(df["timestamp"])
    return df


def _load_expected() -> pd.DataFrame:
    return pd.read_csv(EXPECTED_PATH)


def _run_engine(df: pd.DataFrame) -> list[dict]:
    config = _make_config()
    engine = SignalEngine(config)
    results = []
    for i in range(len(df)):
        slice_ = df.iloc[: i + 1].copy()
        result = engine.generate_signal(slice_)
        results.append({
            "bar_index": i,
            "signal": result["signal"],
            "confidence": result.get("confidence", 0.0),
            "reason": result.get("reason", ""),
        })
    return results


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

class TestGreenblattWeeklyParity:

    def setup_method(self):
        self.df = _load_fixture()
        self.expected = _load_expected()
        self.actual = _run_engine(self.df)

    def test_zero_mismatches(self):
        """AlphaLive must reproduce every AlphaLab signal exactly."""
        mismatches = []
        for _, exp_row in self.expected.iterrows():
            i = int(exp_row["bar_index"])
            exp_sig = exp_row["signal"]
            act_sig = self.actual[i]["signal"]
            if exp_sig != act_sig:
                mismatches.append(
                    f"bar {i}: expected {exp_sig}, got {act_sig} "
                    f"| reason: {self.actual[i]['reason'][:80]}"
                )

        assert mismatches == [], (
            f"{len(mismatches)} mismatch(es):\n" + "\n".join(mismatches)
        )

    def test_buy_signals_match(self):
        """Every BUY produced by AlphaLab must appear in AlphaLive at the same bar."""
        expected_buys = set(
            int(r["bar_index"])
            for _, r in self.expected.iterrows()
            if r["signal"] == "BUY"
        )
        actual_buys = {r["bar_index"] for r in self.actual if r["signal"] == "BUY"}
        assert expected_buys == actual_buys, (
            f"BUY bar mismatch - expected {sorted(expected_buys)}, got {sorted(actual_buys)}"
        )

    def test_sell_signals_match(self):
        """Every SELL produced by AlphaLab must appear in AlphaLive at the same bar."""
        expected_sells = set(
            int(r["bar_index"])
            for _, r in self.expected.iterrows()
            if r["signal"] == "SELL"
        )
        actual_sells = {r["bar_index"] for r in self.actual if r["signal"] == "SELL"}
        assert expected_sells == actual_sells, (
            f"SELL bar mismatch - expected {sorted(expected_sells)}, got {sorted(actual_sells)}"
        )

    def test_no_spurious_signals(self):
        """AlphaLive must not generate signals that AlphaLab did not."""
        expected_non_hold = {
            int(r["bar_index"]): r["signal"]
            for _, r in self.expected.iterrows()
            if r["signal"] != "HOLD"
        }
        for r in self.actual:
            if r["signal"] != "HOLD":
                i = r["bar_index"]
                assert i in expected_non_hold, (
                    f"AlphaLive generated spurious {r['signal']} at bar {i} "
                    f"(not in AlphaLab output)"
                )

    def test_entry_state_resets_correctly(self):
        """After each SELL, the next BUY must be possible (state resets)."""
        signals = [(r["bar_index"], r["signal"]) for r in self.actual if r["signal"] != "HOLD"]
        pairs = list(zip(signals, signals[1:]))
        for (b1, s1), (b2, s2) in pairs:
            if s1 == "SELL":
                assert s2 == "BUY", (
                    f"After SELL at bar {b1}, expected next non-HOLD to be BUY, "
                    f"got {s2} at bar {b2}"
                )

    def test_trailing_stop_fires_before_optional_exits(self):
        """SELL signals must all be trailing-stop exits (optional exits are disabled)."""
        for _, r in self.expected.iterrows():
            if r["signal"] == "SELL":
                assert "trailing stop" in str(r["reason"]).lower(), (
                    f"SELL at bar {int(r['bar_index'])} is not a trailing stop: {r['reason']}"
                )

    def test_min_hold_respected_between_entry_and_trailing_stop(self):
        """Trailing stop can fire before min_hold; all other exits must not."""
        buy_bars  = [int(r["bar_index"]) for _, r in self.expected.iterrows() if r["signal"] == "BUY"]
        sell_bars = [int(r["bar_index"]) for _, r in self.expected.iterrows() if r["signal"] == "SELL"]
        for entry, exit_ in zip(buy_bars, sell_bars):
            hold_weeks = exit_ - entry
            assert hold_weeks >= 1, (
                f"Exit at bar {exit_} fired only {hold_weeks} week(s) after entry at bar {entry} "
                "(trailing stop should need at least 1 bar to move)"
            )

    def test_fixture_has_expected_bar_count(self):
        assert len(self.df) == 522, f"Expected 522 bars, got {len(self.df)}"

    def test_fixture_has_required_columns(self):
        required = {"timestamp", "open", "high", "low", "close", "volume"}
        assert required.issubset(set(self.df.columns)), (
            f"Missing columns: {required - set(self.df.columns)}"
        )

    def test_expected_signal_count(self):
        non_hold = self.expected[self.expected["signal"] != "HOLD"]
        assert len(non_hold) == 5, f"Expected 5 non-HOLD signals, got {len(non_hold)}"

    def test_entry_exit_balance(self):
        buys  = len([r for _, r in self.expected.iterrows() if r["signal"] == "BUY"])
        sells = len([r for _, r in self.expected.iterrows() if r["signal"] == "SELL"])
        assert buys == sells + 1 or buys == sells, (
            f"Unbalanced entries/exits: {buys} BUY, {sells} SELL "
            "(at most 1 open position allowed at end of series)"
        )


# ---------------------------------------------------------------------------
# Parity with exit_rsi_overbought=True - covers the min-hold gated exit path
# ---------------------------------------------------------------------------

EXPECTED_RSI_EXIT_PATH = (
    PROJECT_ROOT / "tests" / "fixtures" / "expected_signals_greenblatt_weekly_rsi_exit.csv"
)


def _make_rsi_exit_config() -> StrategySchema:
    cfg = _make_config()
    cfg.strategy.parameters = {**STRATEGY_PARAMS, "exit_rsi_overbought": True}
    return cfg


def _run_engine_with_min_hold(df: pd.DataFrame) -> list[dict]:
    """Replay with a bar-counting min-hold checker mirroring AlphaLab.

    In production the checker is timestamp-based (BotState.is_min_hold_met);
    here it counts bars since the engine's last BUY so the comparison against
    AlphaLab's bar-counted enforcement is exact.
    """
    engine = SignalEngine(_make_rsi_exit_config())
    hold = {"entry_bar": None, "current_bar": 0}
    engine.min_hold_checker = lambda: (
        hold["entry_bar"] is not None
        and (hold["current_bar"] - hold["entry_bar"]) >= STRATEGY_PARAMS["min_hold_bars"]
    )

    results = []
    for i in range(len(df)):
        hold["current_bar"] = i
        result = engine.generate_signal(df.iloc[: i + 1].copy())
        if result["signal"] == "BUY":
            hold["entry_bar"] = i
        elif result["signal"] == "SELL":
            hold["entry_bar"] = None
        results.append({"bar_index": i, "signal": result["signal"], "reason": result["reason"]})
    return results


class TestGreenblattWeeklyParityRsiExit:
    """Same fixture, exit_rsi_overbought=True.

    This exercises the min-hold gate: AlphaLab's expected signals show the
    RSI exit at bar 105 firing 'after 53w hold' - RSI was overbought earlier
    but the 52-week minimum hold suppressed it. Without the gate, AlphaLive
    would exit early and every subsequent signal would diverge.
    Expected CSV generated from AlphaLab's current code on 2026-07-10.
    """

    def setup_method(self):
        self.df = _load_fixture()
        self.expected = pd.read_csv(EXPECTED_RSI_EXIT_PATH)
        self.actual = _run_engine_with_min_hold(self.df)

    def test_zero_mismatches_with_min_hold_gate(self):
        mismatches = []
        for _, exp_row in self.expected.iterrows():
            i = int(exp_row["bar_index"])
            if exp_row["signal"] != self.actual[i]["signal"]:
                mismatches.append(
                    f"bar {i}: expected {exp_row['signal']}, got {self.actual[i]['signal']} "
                    f"| reason: {self.actual[i]['reason'][:80]}"
                )
        assert mismatches == [], (
            f"{len(mismatches)} mismatch(es):\n" + "\n".join(mismatches)
        )

    def test_rsi_exits_respect_min_hold(self):
        """Every RSI-overbought SELL in the expected set held >= 52 weeks."""
        non_hold = self.expected[self.expected["signal"] != "HOLD"].reset_index(drop=True)
        entry_bar = None
        for _, row in non_hold.iterrows():
            if row["signal"] == "BUY":
                entry_bar = int(row["bar_index"])
            elif "RSI overbought" in str(row["reason"]):
                held = int(row["bar_index"]) - entry_bar
                assert held >= STRATEGY_PARAMS["min_hold_bars"], (
                    f"RSI exit at bar {int(row['bar_index'])} held only {held}w"
                )

    def test_gate_is_load_bearing(self):
        """Without the min-hold gate the engine must exit EARLIER than
        AlphaLab at least once - proving the gate changes behavior and the
        parity above isn't passing vacuously."""
        engine = SignalEngine(_make_rsi_exit_config())  # no checker wired
        first_expected_sell = int(
            self.expected[self.expected["signal"] == "SELL"]["bar_index"].iloc[0]
        )
        for i in range(len(self.df)):
            result = engine.generate_signal(self.df.iloc[: i + 1].copy())
            if result["signal"] == "SELL":
                assert i < first_expected_sell, (
                    "Ungated engine did not exit earlier - fixture no longer "
                    "exercises the min-hold gate; regenerate expected signals"
                )
                return
        pytest.fail("Ungated engine never emitted a SELL")
